### ISSUE TITLE
if i use color codes on mob names but its still white. color codes don't work on mob names

### ISSUE THREAD

**Issue by realistc** [Winds-Studio/DeathMessages#114]
I tried to change the name color of the mob from white to another color but when i do for example &6%killer% it is still white.

**Comment by Dreeam-qwq** [comment]
Can't replicate, try to use latest dev build https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

**Comment by Dreeam-qwq** [comment]
Closed since can't replicate, you can reopen if you can replicate it on latest dev build
