### ISSUE TITLE
[bug/1.12.2] /deathmessages blacklist caused "player is offline"

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#12]
i typed my player name like deathmessages blacklist lClockmanl and nothing

**Comment by F3F5** [comment]
> Can't reproduce. Before you want to add a player to blacklist, be sure that player is online or joined server once at least.

maybe because i disabled playerbase saving

**Comment by Dreeam-qwq** [comment]
> > Can't reproduce. Before you want to add a player to blacklist, be sure that player is online or joined server once at least.
> 
> maybe because i disabled playerbase saving

Yes, if you don't enable `Saved-User-Data` option in Settings.yml, you can't use /dm blacklist and /dm toggle command.

**Comment by F3F5** [comment]
@Dreeam-qwq currently i dont have issues after 10014024020 issues, but have question 
if i remember in normal deathmessages not a fork i can use death message blacklist <playername> with Saved-User-Data false and after restart it resets, can u check or add this feautre (if im wrong)

**Comment by Dreeam-qwq** [comment]
> @Dreeam-qwq currently i dont have issues after 10014024020 issues, but have question if i remember in normal deathmessages not a fork i can use death message blacklist with Saved-User-Data false and after restart it resets, can u check or add this feautre (if im wrong)

I'll check this later.

**Comment by F3F5** [comment]
thanks

**Comment by F3F5** [comment]
tomorrow i can check <3

**Comment by F3F5** [comment]
> Added in [cc92ebf](https://github.com/Winds-Studio/DeathMessages/commit/cc92ebfe4900f3b1472e1a12df07036f6e87ec1e) Now, you can use both Blacklist and Toggle commands when the `Saved-User-Data` is disabled

toggle commands already i can use
only blacklist can't
currently testing this change

**Comment by F3F5** [comment]
no problems
