### ISSUE TITLE
Flood in kill wolfs in latest dev build

### ISSUE THREAD

**Issue by thiagogebrimm** [Winds-Studio/DeathMessages#120]
![image](https://github.com/user-attachments/assets/9e8f7546-38e9-40b8-a370-0d8b84214fb8)

**Comment by Dreeam-qwq** [comment]
BC hook issue

**Comment by Dreeam-qwq** [comment]
Can you provide your DeathMessages config using https://mclo.gs and also your DeathMessages version?

**Comment by Dreeam-qwq** [comment]
Can't replicate, but the one duplicated message issue is fixed in https://github.com/Winds-Studio/DeathMessages/commit/dc77b190ec18cfb8c5aa3397c0ae1377d5da1dc8
