### ISSUE TITLE
Some bugs and feature requests

### ISSUE THREAD

**Issue by TymekSL** [Winds-Studio/DeathMessages#123]
DeathMessages 
default option to set color of: killer, of mob and default text color (now all is on white ;/) 

Update notifier with custom message 

Items placeholders? (how many items are in the chest)

Support for level mobs and healthbar bossbar https://prnt.sc/tdNcKg6DeC5v

**Comment by Dreeam-qwq** [comment]
1. duplicate with https://github.com/Winds-Studio/DeathMessages/issues/114 , can’t replicate this issue
2. Not necessarily, update notifications only show in the console
3. duplicate with https://github.com/Winds-Studio/DeathMessages/issues/47

**Comment by TymekSL** [comment]
no no no, its not duplicate 
option will be 
default_color: "&e"

**Comment by Dreeam-qwq** [comment]
> no no no, its not duplicate option will be default_color: "&e"

You can define color for each mob name, in config like `&4%player%&3 killed by&6%killer%&3`, I don't think it's necessary to add default color. You can use text editor's find and replace function to add color for all mob names in the config

**Comment by Dreeam-qwq** [comment]
See https://github.com/Winds-Studio/DeathMessages/issues/135
