### ISSUE TITLE
[permission] sub-command

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#13]
maybe make perm for sub command? because i allowed only blacklist and toggle command
![image](https://github.com/Winds-Studio/DeathMessages/assets/108226177/a66f2195-7b2f-42e7-bc0c-b7ee04a997aa)

but with tab-complete i see other commands too

**Comment by Dreeam-qwq** [comment]
Added in 3f47a5c10833bb5b807fd386b18eb16a4cbbd087
For every permission nodes you added in previous time, you need to update them, like
`deathmessages.command.deathmessages.backup` -> `deathmessages.command.backup`

**Comment by F3F5** [comment]
better and simply :) thank you

**Comment by F3F5** [comment]
good
