### ISSUE TITLE
%killer% placeholder in deathmessage not working sometimes

### ISSUE THREAD

**Issue by homerek111** [Winds-Studio/DeathMessages#132]
while using this version you sent me here https://discord.com/channels/604562446325383168/959842504440680499/1277790478036766771 sometimes i see messages without properly specified %killer% placeholder

![obraz](https://github.com/user-attachments/assets/e178c44e-97e1-4e79-880f-3202f8b2d6c4)

i try to re-download the dev-build as i see there is some change 1 week ago so maybe it's fixed already - if not i'm reporting :)

[18:20:28] [Server thread/INFO]: » Marinaa02 ☠ zginął od %killer% (Extra: World:Oneblock, X:-1198, Y:100, Z:602)

I also found one situation where Spider mob was counted as a player and message from player kills was triggered instead of Spider's one

server versin: This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z)

I have no idea how these cases happened - i just saw them randomly in log / on chat

**Comment by sannielollie** [comment]
Im seeing this happening too, but with spawners. Im using SilkSpawners plugin, but it also happens with pre-generated spawners. When (for example) a cavespider spawns from a naturally generated spawner kills a player, it says player is slain by %killer% or pushed from a high place by %killer% and so on.

**Comment by Dreeam-qwq** [comment]
Can you try to enable `Debug` in `Settings.yml` ? it will print death type of that death, maybe easier to address the issue. (

**Comment by Dreeam-qwq** [comment]
Closed since can't replicate, reopen or create new one if you still have this issue.
