### ISSUE TITLE
option to players name instead of bar

### ISSUE THREAD

**Issue by TymekSL** [Winds-Studio/DeathMessages#135]
option to players name instead of bar
 using healtbar reloaded and deathmessages and got 
https://prnt.sc/huad3E9RnbsW

totally doesn't work as i would, could you add any option to fix it?

**Comment by Dreeam-qwq** [comment]
Provide link of plugin you want DeathMessages to support with.

**Comment by TymekSL** [comment]
https://www.spigotmc.org/resources/healthbar-reloaded.104616/

**Comment by Dreeam-qwq** [comment]
> https://www.spigotmc.org/resources/healthbar-reloaded.104616/

Did you tried to use %player% as player name placeholder, and use %killer% as mob name placeholder?

**Comment by TymekSL** [comment]
in the deathmessages? yes all messages have %player%

**Comment by Dreeam-qwq** [comment]
> %killer%

Yes, in deathmessages config, for your death messages try to use %player% as player name placeholder instead of using %player_display%, and use %killer% as mob name placeholder instead using %killer_display%

**Comment by Dreeam-qwq** [comment]
Use %killer_type% to replace the %killer%, the name of mob will display correctly. Closed
