### ISSUE TITLE
bug showing multiple death messages when dying

### ISSUE THREAD

**Issue by patrick323** [Winds-Studio/DeathMessages#143]
Hello, when a player dies, it shows the custom message and the server message at the same time. The command /gamerule showDeathMessage false was executed, but it was not successful.
I am using the latest version of the plugin [v1.4.19] and paper.
option has true Disable-Default-Messages: true 
the command was executed /gamerule showDeathMessage false but dont work
pictures examples:
https://cdn.discordapp.com/attachments/959842504440680499/1297735287442771998/image.png?ex=671701ab&is=6715b02b&hm=006d085525c3880bee37635fb79f8fc2a45ba4284607d6bba6e881171012d7b0&

https://cdn.discordapp.com/attachments/959842504440680499/1297735287698358352/image.png?ex=671701ab&is=6715b02b&hm=20cd2a370814027b2f5a80c81616baea8413733b1015803bf93cdf8ecf566a20&

**Comment by Dreeam-qwq** [comment]
Pictures down, and please try latest build in GitHub ACtion

**Comment by Dreeam-qwq** [comment]
Closed since can not replicate
