### ISSUE TITLE
Brak koloru w niektorych miejscach

### ISSUE THREAD

**Issue by Tobiczek** [Winds-Studio/DeathMessages#151]
### Checklist

- [X] I have searched the existing issues
- [X] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

[](https://prnt.sc/McWY5_M_58PA)](https://prnt.sc/McWY5_M_58PA)

https://pastebin.com/xkywJXzv

https://prnt.sc/JntHu7k07tgT

### Expected behaviour

Appearance of colour

In these examples, to be precise, it does not change the name of the mob to Polish

I added for example -  cave_spider , zombie_villager.

in both files and it worked when I typed reload, but when there was a restart it reset itself as it was without the _ and again does not work as it only writes with these 2 things

### To Reproduce

purpur 1.21.1 

Generally there is no bug, it just doesn't catch it along with some mobs

### Spark profiler link

https://spark.lucko.me/l2nRR103F5

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Added missing entity types to the list in EntityUtil class, including cave_spider and zombie_villager. Updated the list to use underscores for compound names to match Minecraft's entity naming convention. Also added a TODO comment to remind about updating to the newest version.

I also created pull request: https://github.com/Winds-Studio/DeathMessages/pull/152


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by Dreeam-qwq** [comment]
Can you provide all your DeathMessages configs, except UserData.yml? paste them in https://mclo.gs/
And can you provide steps to replicate this issue more specific? Like `in both files`, which files (

**Comment by Tobiczek** [comment]
[Jak to wszystko to mozesz zamknac ticket](https://prnt.sc/fiHnqteCF5HT)

etc., I have these things translated, but something is not catching

**Comment by Tobiczek** [comment]
[archive-2024-11-09T120637+0100.tar.gz](https://github.com/user-attachments/files/17686899/archive-2024-11-09T120637%2B0100.tar.gz)

**Comment by Dreeam-qwq** [comment]
> [Jak to wszystko to mozesz zamknac ticket](https://prnt.sc/fiHnqteCF5HT)
> 
> etc., I have these things translated, but something is not catching

If you want to use translated name in `Message.yml`, you need to use `%killer_type%` placeholder, instead of `%killer%`
, using `%killer%` will use i18n name based on client language.
![image](https://github.com/user-attachments/assets/54d5bae1-b76f-4616-a410-ab5622a6f0d0)

**Comment by Tobiczek** [comment]
Okey okey!, and I have a question, how is that? the colour of the weapon?

**Comment by Dreeam-qwq** [comment]
> Okey okey!, and I have a question, how is that? the colour of the weapon?

Weapon color has no issue, if you config correctly, it can display correctly

Try to use hex color code for your %weapon%, like you did for other placeholders.
Use formate like `&#FBD640%weapon%`, should work fine.

**Comment by ArduFish** [comment]
Lol the second checkbox.

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/d2c963ca3d3fcfd4ed92f3ad873c3600a0fe5d42
