### ISSUE TITLE
Removing "DeathMessages" logo from startup

### ISSUE THREAD

**Issue by RedstoneFuture** [Winds-Studio/DeathMessages#157]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest dev build from https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

### What behaviour is observed?

Hello, with all normal self-promotion, such typographic labels that are written in the log in large quantities are not nice. I would be very happy if the message is removed from the startup. 🙂

The log is used for administrative work. It should only contain important messages.

```
[23:49:23] [Server thread/INFO]: [DeathMessages] Enabling DeathMessages v1.4.20
--> [23:49:23] [Server thread/INFO]: 
    ____             __  __    __  ___                                    
   / __ \___  ____ _/ /_/ /_  /  |/  /__  ______________ _____ ____  _____
  / / / / _ \/ __ `/ __/ __ \/ /|_/ / _ \/ ___/ ___/ __ `/ __ `/ _ \/ ___/
 / /_/ /  __/ /_/ / /_/ / / / /  / /  __(__  |__  ) /_/ / /_/ /  __(__  ) 
/_____/\___/\__,_/\__/_/ /_/_/  /_/\___/____/____/\__,_/\__, /\___/____/  
                                                       /____/             
```

https://github.com/Winds-Studio/DeathMessages/blob/1adeab4d49f5ac31481542f3975408b2296835b4/Core/src/main/java/dev/mrshawn/deathmessages/DeathMessages.java#L303-L310

### Expected behaviour

Only this message on startup:

```
[23:49:23] [Server thread/INFO]: [DeathMessages] Enabling DeathMessages v1.4.20
```

At most other important(!) information.

### To Reproduce

With normal server startup.

```
Debug: false
```

### Spark profiler link

This is not helpful for this report.

**Comment by Dreeam-qwq** [comment]
I don't see this suggestion makes any sense.

btw, it should be a "feature request", instead of a "bug".

**Comment by RedstoneFuture** [comment]
It is actually a refactoring request and not a feature request. After all, no feature is to be added. But you don't have this label. ;)

The purpose is to keep the console and the log clean and not to throw in gigantic text logos.

**Comment by Dreeam-qwq** [comment]
Removed in https://github.com/Winds-Studio/DeathMessages/commit/96a2e2bfabd24bf79718bb9623df6002a85ce78d
