### ISSUE TITLE
Wrong weapon result for fireball by ghast

### ISSUE THREAD

**Issue by RedstoneFuture** [Winds-Studio/DeathMessages#159]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest dev build from https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

### What behaviour is observed?

When I am fired at by the Ghast with fireballs, the Weapon is “AIR” instead of [Fireball](https://minecraft.wiki/w/Ghast#Fireball) (`minecraft:fireball`).

`[00:58:28] [Server thread/INFO]: [DM] RedstoneFuture was shot by a Ghast somehow using Air (Extra: World:world_nether, X:1, Y:71, Z:-9)`

![grafik](https://github.com/user-attachments/assets/36c4e2e5-655f-45a8-b3aa-d38903e70c84)

### Expected behaviour

`[...] by a Ghast somehow using Fireball`

### To Reproduce

Let the [Ghast](https://minecraft.wiki/w/Ghast) shoot at you. But don't die from lava or fire.

**Tested with 1.4.20-SNAPSHOT**

### Spark profiler link

-

### DeathMessages configuration (if applicable)

default config

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/77d90dc845790763bb38a0dd5fbda340be130759
