### ISSUE TITLE
When a player gets slain by a Mace and I try to display the weapon name it just stays at %weapon%. 

### ISSUE THREAD

**Issue by Pman3** [Winds-Studio/DeathMessages#160]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest dev build from https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

### What behaviour is observed?

![image](https://github.com/user-attachments/assets/aa17a210-6ee2-49a5-8b21-a25e471f8a22)
When a player slays another player with a mace, instead of displaying the killing weapon, it just shows %weapon%. This probably happens for other tools too but this config is the one at the very bottom and last melee config.

### Expected behaviour

It's supposed to just print of mace with the enchants on the item but it's not what's happening.

### To Reproduce

In PlayerDeathMessages config under the player->solo->melee if I add %weapon% to this when I slay someone with a mace it just shows up as %weapon%

### Spark profiler link

https://spark.lucko.me/RrH9oqqtkJ

### DeathMessages configuration (if applicable)

https://mclo.gs/gezmCCv

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/85a1ec08c222896fed9baaccf0397b512ea0bbe7
