### ISSUE TITLE
Huge error message in console and death message isn't sent at all when a player dies in any way which relates to 'blowing up'

### ISSUE THREAD

**Issue by Pman3** [Winds-Studio/DeathMessages#161]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest dev build from https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

### What behaviour is observed?

When a player blows up from an end crystal or wither (from what ive seen so far, i believe there's other things that cause this too) the death message is sent in the console but its not sent in my discord or in-game. 

### Expected behaviour

It's supposed to be sent in the discord and appear in game normally without any errors in my console.

### To Reproduce

For example, you can log in and get a crystal and blow yourself up or with enough tried from a wither and eventually I get the issue of the message not being received in game or in the discord server through DiscordSRV.

### Spark profiler link

https://spark.lucko.me/RrH9oqqtkJ

### Error log (if applicable)

https://mclo.gs/fDzYUI6

### DeathMessages configuration (if applicable)

https://mclo.gs/fQLf1hK

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/4030308aa7e2cb5de1031a48b2ffa29374f9e5aa, please test
