### ISSUE TITLE
玩家被弓射杀不会正常显示死亡信息

### ISSUE THREAD

**Issue by Leleawa** [Winds-Studio/DeathMessages#170]
### 自我检查表

- [X] 我已经浏览过Issue, 并确保汇报的不是已知问题
- [ ] 我勾选了所有框, 因为我根本就没仔细看他们是什么
- [X] 我正在使用从 https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build 下载的最新 DeathMessages 开发版构建

### 问题描述

玩家被弓射杀不会正常显示死亡信息，后台有报错

### 所期望的行为

正常显示死亡信息，后台没有报错

### 如何复现？

1.运行一个Folia1.21.4服务器
2.安装DeathMessages
3.一个入给另一个入用弓射死
4.后台报错，不显示死亡信息

### Spark profiler 链接

https://spark.lucko.me/15nRXfQ2hM

### 错误日志 (如存在)

https://mclo.gs/GcpQtNB

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/6e134b7a88fdafd47a9cd99a75695aae120fb55a, try the latest dev build
