### ISSUE TITLE
When someone is killed from a fist the death message is %weapon%

### ISSUE THREAD

**Issue by Pman3** [Winds-Studio/DeathMessages#171]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest dev build from https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

### What behaviour is observed?

When a player on my server killed another player on my server by just fisting them, the following message appeared: (player1) was slain by (player2) somehow using %weapon%.

My server is on 1.21.3 so i dont know if it something from the version but I am using the latest build so I dont know what could be causing this issue.

### Expected behaviour

Its not supposed to pick this message since a fist isnt a weapon and it should just say (player) was slain by (player2).... for example.

### To Reproduce

Go in a server and just kill someone with a fist on the latest build on PaperMC's latest 1.21.3 build (#81).

### Spark profiler link

https://spark.lucko.me/EoCBITKmWd

**Comment by Dreeam-qwq** [comment]
Can not replicate
![image](https://github.com/user-attachments/assets/5ece1374-061e-4909-8483-0a3b3e732678)

Please try the latest dev build and provide your death messages config

**Comment by Pman3** [comment]
Oh okay it was an issue on my side. I had added %weapon% at the end of Mobs.play.Solo.Melee for some reason. I removed it and it works perfectly!
