### ISSUE TITLE
[color] is it normal?

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#18]
i only have for weapon this color, but why color in the extra
![Screenshot_1](https://github.com/Winds-Studio/DeathMessages/assets/108226177/c837e4d1-4e5e-4a4e-ae8b-cc9b09a7495c)

**Comment by Dreeam-qwq** [comment]
It should be no color, unless you define a color in config like `%message% &b(Extra…..`

**Comment by F3F5** [comment]
> It should be no color, unless you define a color in config like `%message% &b(Extra…..`

  Message: "%message% (Extra: World:%world%, X:%x%, Y:%y%, Z:%z%)"

**Comment by F3F5** [comment]
bug..

**Comment by F3F5** [comment]
fixed , confirmed
