### ISSUE TITLE
[1.12.2] NoClassDefFoundError

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#2]
error: https://pastes.dev/H7DxMRmqQw
killed by shulkers

**Comment by Dreeam-qwq** [comment]
Thanks reporting bug! I'm checking this.

**Comment by Dreeam-qwq** [comment]
Fixed in d2d07e98ce443a9fd67bd4d7eead81879070192a...314c1c4dce6503482bae8720bf535467fc69b463
