### ISSUE TITLE
PowerShell Build Issues 

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#35]
* What went wrong:
Execution failed for task ':compileKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileJava' (17) and 'compileKotlin' (21).

(Intelij idea with 'build' button no problems) BUILD SUCCESSFUL in 19s
6 actionable tasks: 6 executed
13:23:34: Execution finished 'build'.

**Comment by Dreeam-qwq** [comment]
Fixed in 1dd5da080ab8586a9c259965ff213c1fae97a859

**Comment by F3F5** [comment]
confirmed

**Comment by Dreeam-qwq** [comment]
After commit b5b29d9fd25c91dc32af04f8c153041cf51246f1

There is only one Jar in the buil/libs folder, so no need to make time to find which one should to use now

**Comment by F3F5** [comment]
> After commit [b5b29d9](https://github.com/Winds-Studio/DeathMessages/commit/b5b29d9fd25c91dc32af04f8c153041cf51246f1)
> 
> There is only one Jar in the buil/libs folder, so no need to make time to find which one should to use now

good
