### ISSUE TITLE
Add support for EcoEnchants

### ISSUE THREAD

**Issue by michael-b-jordan** [Winds-Studio/DeathMessages#45]
Can you add support for EcoEnchants so custom enchantments and lore can show up in weapons?
![image](https://github.com/Winds-Studio/DeathMessages/assets/129551266/d07d31fb-7617-4ddd-8316-2ba9d88c1270)

**Comment by Dreeam-qwq** [comment]
Can you try add [NBT API plugin](https://github.com/tr7zw/Item-NBT-API)?

**Comment by Dreeam-qwq** [comment]
Added in 7909514817b5f93d919e5e3afcbe8336f66e961d

**Comment by Dreeam-qwq** [comment]
> > Added EcoEnchants support in [7909514](https://github.com/Winds-Studio/DeathMessages/commit/7909514817b5f93d919e5e3afcbe8336f66e961d) Yeah!!!
> 
> Hmm seem to be getting this issue on the latest build. Players death messages being killed by other players do not show.
> 
> ```
> java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R2.enchantments.CraftEnchantment cannot be cast to class com.willfp.ecoenchants.enchant.EcoEnchantLike (org.bukkit.craftbukkit.v1_20_R2.enchantments.CraftEnchantment is in unnamed module of loader java.net.URLClassLoader @5ce65a89; com.willfp.ecoenchants.enchant.EcoEnchantLike is in unnamed module of loader 'EcoEnchants v11.1.0.jar' @2c913c32)
>         at dev.mrshawn.deathmessages.hooks.EcoExtension.getEcoEnchantsItem(EcoExtension.java:93) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at dev.mrshawn.deathmessages.utils.Assets.buildHover(Assets.java:752) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at dev.mrshawn.deathmessages.utils.Assets.getWeapon(Assets.java:405) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at dev.mrshawn.deathmessages.utils.Assets.playerDeathMessage(Assets.java:182) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at dev.mrshawn.deathmessages.listeners.EntityDeath.lambda$onEntityDeath$0(EntityDeath.java:105) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
>         at dev.mrshawn.deathmessages.listeners.EntityDeath.onEntityDeath(EntityDeath.java:46) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at dev.mrshawn.deathmessages.listeners.EntityDeath.onEntityDeath_HIGH(EntityDeath.java:189) ~[DeathMessages-1.4.18-SNAPSHOT.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1226.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:993) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:961) ~[?:?]
>         at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
>         at net.minecraft.world.entity.player.Player.hurt(Player.java:973) ~[?:?]
>         at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1130) ~[?:?]
>         at net.minecraft.world.entity.player.Player.attack(Player.java:1326) ~[?:?]
>         at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2181) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2778) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2702) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
>         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
>         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
>         at java.lang.Thread.run(Thread.java:840) ~[?:?]```
> ```

Thanks, will look into this in these days

**Comment by Dreeam-qwq** [comment]
Fixed in 1b022d5c2151d74f7de34e6ab1355094038af470
