### ISSUE TITLE
Unable to display the lore and enchantment of items

### ISSUE THREAD

**Issue by Pen92he** [Winds-Studio/DeathMessages#46]
![image](https://github.com/Winds-Studio/DeathMessages/assets/96214684/4bd4f7ef-39d3-4190-ae05-746fa59c63a0)
![image](https://github.com/Winds-Studio/DeathMessages/assets/96214684/7d73126e-988c-4546-9b1b-d9e9e3747ad1)
![image](https://github.com/Winds-Studio/DeathMessages/assets/96214684/b464131a-dc71-4e39-864b-e20be9cfbdcd)
As shown in the figure, the lore, enchantment, and name of the item do not exist in the hover display

**Comment by Dreeam-qwq** [comment]
lore和物品名字是什么插件搞得呢

**Comment by Pen92he** [comment]
这个插件好像原本就有显示lore和名字的功能，我用这插件两年了，是从1.20开始不显示的

**Comment by Pen92he** [comment]
好吧，装上nbtapi问题得以解决

**Comment by Dreeam-qwq** [comment]
> 好吧，装上nbtapi问题得以解决

想了一下，DeathMessage其实已经内置NBT API了，再加个是否装了NBT API的检测没必要，下一个commit我去掉这个检测就好了

**Comment by Dreeam-qwq** [comment]
好了 7a2a8435fbe4d5ef24410c73bf394fb81f306665, 试一下最新的[构建](https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build) 不用加NBT API也能正常显示物品名字和lore等物品nbt数据了
