### ISSUE TITLE
death message after player typing a command

### ISSUE THREAD

**Issue by cupang-afk** [Winds-Studio/DeathMessages#50]
i have command called `/sudoku`
and i want to set a message for it 

if its already implemented let me know because i dont see much of the config (i only change the basic config)

**Comment by Dreeam-qwq** [comment]
You mean add a new feature, to let player to run the command after they die?

**Comment by cupang-afk** [comment]
> You mean add a new feature, to let player to run the command after they die?

no i mean if player type `/sudoku` in chat, the command will kill the player
i want to customize this death message (death because a command)

as for now, when typing `/sudoku` the death message will show as natural cause and this can be random depend on what player were doing (but most of the time it use Custom section)

**Comment by Dreeam-qwq** [comment]
If you added custom kill/suicide command in your plugin, you need set damage cause to `DamageCause.SUICIDE` before using `setHealth(0);`, just like what Essentials did, https://github.com/EssentialsX/Essentials/blob/c85e179718944d3482a223c6f459b7149cab9b83/Essentials/src/main/java/com/earth2me/essentials/commands/Commandsuicide.java#L17C118-L17C137

But anyway, I will add an option in config that you can add your custom suicide commands. When player died using these commands, the death message of the death will be the suicide.

**Comment by Dreeam-qwq** [comment]
Added in https://github.com/Winds-Studio/DeathMessages/commit/07a458e7c6084b804575f42cf3d7408fc98a9eed, now you can add your custom suicide command in `Custom-Suicide-Commands` of `Settings.yml`
