### ISSUE TITLE
Death message results in item.minecraft ? 

### ISSUE THREAD

**Issue by michael-b-jordan** [Winds-Studio/DeathMessages#53]
![image](https://github.com/Winds-Studio/DeathMessages/assets/129551266/c14698f2-d542-428c-bc15-e3da3cfc7b91)

**Comment by Dreeam-qwq** [comment]
Yes, the i18n item name and mob name need to redesign, to be compatible with the displays in DiscordSRV and for bedrock players if the server is using Geyser.

**Comment by Dreeam-qwq** [comment]
Fixed in 2cba2e9b4947ffea9beeea417231eef506aa20aa

**Comment by Dreeam-qwq** [comment]
> hmm seems like it says diamond_sword now instead of Diamond Sword ![image](https://private-user-images.githubusercontent.com/129551266/328317345-221bd3d5-60c5-46ec-853c-17b2572df07f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDQzMjAsIm5iZiI6MTcxNTA0NDAyMCwicGF0aCI6Ii8xMjk1NTEyNjYvMzI4MzE3MzQ1LTIyMWJkM2Q1LTYwYzUtNDZlYy04NTNjLTE3YjI1NzJkZjA3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMTA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDViYWUzNzkzZGE2MDQ3YmI2MGY4YmNmMTY3NzkzM2UyM2QxZTk4MDQ1ZWViNGFjZDExNjE3ZGY3NTI0ZDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfngNDIxspk8zMElwDpaZTqLLvHYsY19YO6nCP_Pqz8)

Well, it is expected, but I decide to reopen this until it got really fixed

**Comment by Dreeam-qwq** [comment]
Temp fix in 914727cbc20bdafef6712e920bff36670da8d4b1

**Comment by Dreeam-qwq** [comment]
Closed. Just disable i18n display feature if using DiscordSRV to send death messages to dicord.
