### ISSUE TITLE
[Bug] DiscordSRV death message overly substringed

### ISSUE THREAD

**Issue by EarthCow** [Winds-Studio/DeathMessages#55]
When the configuration option `Discord.DeathMessage.Remove-Plugin-Prefix` is enabled the death messages are being substringed too far.

![image](https://github.com/Winds-Studio/DeathMessages/assets/56940983/401a467c-93d2-4af3-8808-e1971173ab37)

This is likely caused by the use of color codes in the prefix and the wrong length being used here: https://github.com/Winds-Studio/DeathMessages/blob/15f4a0a0155a7331c7930e1ee7116dad4e92071b/Core/src/main/java/dev/mrshawn/deathmessages/hooks/DiscordSRVExtension.java#L65 or here: https://github.com/Winds-Studio/DeathMessages/blob/15f4a0a0155a7331c7930e1ee7116dad4e92071b/Core/src/main/java/dev/mrshawn/deathmessages/hooks/DiscordSRVExtension.java#L114 That's just speculation though.

I'm not sure if this is only on newer versions but I discovered the bug on a 1.20.4 paper server using version 1.4.18 of the plugin.

**Comment by Dreeam-qwq** [comment]
Fixed in 70b60147ecbdf9e673c4a865ea20320646a8b47d
