### ISSUE TITLE
Death message permissions?

### ISSUE THREAD

**Issue by ghost** [Winds-Studio/DeathMessages#59]
Yo, did you update the permissions cause I tried both `deathmessages.command.deathmessages.toggle` and `deathmessages.command.toggle` but default players can't seem to /dmtoggle compared to the original DeathMessages plugin. It just returns "You do not have permission for this command."

**Comment by Dreeam-qwq** [comment]
Should be fixed in https://github.com/Winds-Studio/DeathMessages/commit/53d8f29504418e4ad6941dffb7bbc39bd8b0a541
