### ISSUE TITLE
Messages.yml gets filled with text

### ISSUE THREAD

**Issue by the-n1n** [Winds-Studio/DeathMessages#67]
Messages.yml gets filled with text to the point it halts server restarts. For me, the text file was filled with 153 million characters and is around 170 MB & 70 MB respectively (2 Servers)

I've uploaded a version of it where about 47 lines of the longest part remain, note there were hundreds of thousands of these lines but Github has a 25 MB max. it's also nor
[Messages.txt](https://github.com/user-attachments/files/16023425/Messages.txt)

**Comment by Dreeam-qwq** [comment]
known issue, please see https://github.com/Winds-Studio/DeathMessages/issues/49

For now, the temp solution is to reset Messages.yml
