### ISSUE TITLE
[error] DeathMessages v1.4.18-SNAPSHOT generated an exception while executing task 

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#8]
error: https://pastes.dev/DAN4R6BUk4

**Comment by Dreeam-qwq** [comment]
How to reproduce it? Or just random spam in the console

**Comment by F3F5** [comment]
i dont know restarted server, players joined = error

**Comment by Dreeam-qwq** [comment]
> i dont know restarted server, players joined = error

remember to delete all DeathMessages config and let it regenerate.
